import {
  Category,
  Dish,
  ServiceItem,
  Testimonial,
  RestaurantInfo,
  NotificationItem,
  SupportRequest,
  ContactMessage,
  UserProfile,
  DeliveryPerson,
  Order,
  DeliveryAddress,
} from "@/types";

export const initialRestaurantInfo: RestaurantInfo = {
  id: "rest-001",
  restaurant_name: "Riwaayat",
  tagline: "Where Tradition Meets Taste",
  logo_url: "/images/logo.jpg",
  description:
    "Riwaayat celebrates the timeless heritage of Indian hospitality, royal culinary secrets, and grandmother's recipes. From aromatic clay oven tandoors to fragrant dum biryanis, experience the rich flavours and warm traditions of India.",
  address: "Heritage Haveli, Palace Road, Civil Lines, Jaipur 302006, Rajasthan, India",
  phone: "+91 141 289 4400",
  email: "namaste@riwaayat-dining.com",
  opening_hours: "Monday – Sunday: 11:30 AM – 3:30 PM & 7:00 PM – 11:30 PM",
  updated_at: new Date().toISOString(),
};

export const initialCategories: Category[] = [
  {
    id: "cat-north-indian",
    name: "North Indian",
    slug: "north-indian",
    description: "Rich gravies, aromatic whole spices, tandoori specialties and slow-simmered culinary classics.",
    image_url: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80",
    dish_count: 8,
    status: "active",
    display_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-south-indian",
    name: "South Indian",
    slug: "south-indian",
    description: "Crispy fermented dosas, steamed idlis, fragrant sambar, tangy rasam, and coconut-infused coastal curries.",
    image_url: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80",
    dish_count: 5,
    status: "active",
    display_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-mughlai",
    name: "Mughlai",
    slug: "mughlai",
    description: "Imperial culinary heritage slow-cooked in handis with cashews, cream, saffron, and aromatic rosewater.",
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
    dish_count: 6,
    status: "active",
    display_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-rajasthani",
    name: "Rajasthani",
    slug: "rajasthani",
    description: "Authentic Marwari & Rajputana delicacies slow-cooked with pure ghee, desert beans, and stone-ground grains.",
    image_url: "/images/dishes/dal-baati-churma.jpg",
    dish_count: 4,
    status: "active",
    display_order: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-punjabi",
    name: "Punjabi",
    slug: "punjabi",
    description: "Robust, hearty flavours straight from Punjab's tandoors, loaded with churned white butter and aromatic kasuri methi.",
    image_url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
    dish_count: 6,
    status: "active",
    display_order: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-biryani",
    name: "Biryani",
    slug: "biryani",
    description: "Aged long-grain basmati rice slow-cooked in sealed earthen pots (dum) with saffron, mint, and secret spice potli.",
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    dish_count: 5,
    status: "active",
    display_order: 6,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-tandoor",
    name: "Tandoor",
    slug: "tandoor",
    description: "Clay-oven roasted kebabs and skewered tikka marinated in hung curd, Kashmiri deghi mirch, and mustard oil.",
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80",
    dish_count: 6,
    status: "active",
    display_order: 7,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-indian-breads",
    name: "Indian Breads",
    slug: "indian-breads",
    description: "Handcrafted Naans, Parathas, and Rotis slapped onto glowing clay tandoor walls and brushed with desi ghee.",
    image_url: "/images/dishes/garlic-naan.jpg",
    dish_count: 6,
    status: "active",
    display_order: 8,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-curries",
    name: "Curries",
    slug: "curries",
    description: "Velvety spiced tomato gravies, coconut broths, and onion-cashew kormas simmered to perfection.",
    image_url: "/images/dishes/paneer-butter-masala.jpg",
    dish_count: 8,
    status: "active",
    display_order: 9,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-vegetarian",
    name: "Vegetarian",
    slug: "vegetarian",
    description: "Wholesome vegetarian delicacies prepared with fresh malai paneer, farm vegetables, and rich dals.",
    image_url: "/images/dishes/hara-bhara-kebab.jpg",
    dish_count: 10,
    status: "active",
    display_order: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-non-veg",
    name: "Non-Vegetarian",
    slug: "non-vegetarian",
    description: "Succulent chicken, slow-cooked tender mutton, and regional fish preparations steeped in heritage marinades.",
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80",
    dish_count: 8,
    status: "active",
    display_order: 11,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-starters",
    name: "Snacks & Starters",
    slug: "snacks-starters",
    description: "Crispy golden savories, aromatic patties, and melt-in-the-mouth kebabs served with tangy mint chutney.",
    image_url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
    dish_count: 7,
    status: "active",
    display_order: 12,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-rice",
    name: "Rice & Pulao",
    slug: "rice-pulao",
    description: "Fragrant basmati rice gently tempered with roasted cumin, whole spices, dry fruits, and saffron.",
    image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    dish_count: 4,
    status: "active",
    display_order: 13,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-desserts",
    name: "Desserts",
    slug: "desserts",
    description: "Traditional Indian sweets made with reduced milk (khoya), cardamom, saffron, and pure pistachio nuts.",
    image_url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    dish_count: 6,
    status: "active",
    display_order: 14,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-beverages",
    name: "Beverages",
    slug: "beverages",
    description: "Traditional refreshments, slow-simmered Masala Chai, thick curd lassis, and chilled digestifs.",
    image_url: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    dish_count: 6,
    status: "active",
    display_order: 15,
    created_at: new Date().toISOString(),
  },
];

export const initialDishes: Dish[] = [
  // ---------------- STARTERS & TANDOOR ----------------
  {
    id: "dish-01",
    category_id: "cat-tandoor",
    category_name: "Tandoor",
    name: "Paneer Tikka",
    description: "Cubes of fresh malai paneer marinated in spiced hung curd, bell peppers, and roasted in a charcoal clay oven.",
    price: 260,
    image_url: "/images/dishes/paneer-tikka.jpg",
    image: "/images/dishes/paneer-tikka.jpg",
    rating: 4.9,
    reviews_count: 142,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-02",
    category_id: "cat-starters",
    category_name: "Snacks & Starters",
    name: "Hara Bhara Kebab",
    description: "Crisp patties crafted from fresh spinach, green peas, mashed potatoes, and roasted aromatic spices.",
    price: 240,
    image_url: "/images/dishes/hara-bhara-kebab.jpg",
    image: "/images/dishes/hara-bhara-kebab.jpg",
    rating: 4.7,
    reviews_count: 88,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-03",
    category_id: "cat-starters",
    category_name: "Snacks & Starters",
    name: "Dahi Ke Kebab",
    description: "Melt-in-the-mouth shallow-fried kebabs made from hung curd, grated paneer, cardamom, and roasted gram flour.",
    price: 250,
    image_url: "/images/dishes/dahi-ke-kebab.jpg",
    image: "/images/dishes/dahi-ke-kebab.jpg",
    rating: 4.8,
    reviews_count: 94,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-04",
    category_id: "cat-tandoor",
    category_name: "Tandoor",
    name: "Chicken Tikka",
    description: "Boneless chicken morsels marinated in Kashmiri chili, ginger-garlic paste, hung curd, and roasted over red embers.",
    price: 320,
    image_url: "/images/dishes/chicken-tikka.jpg",
    image: "/images/dishes/chicken-tikka.jpg",
    rating: 4.9,
    reviews_count: 175,
    is_veg: false,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-05",
    category_id: "cat-tandoor",
    category_name: "Tandoor",
    name: "Tandoori Chicken",
    description: "Whole chicken quarter cuts bathed in mustard oil marinade, crushed roasted coriander, and tandoori garam masala.",
    price: 350,
    image_url: "/images/dishes/tandoori-chicken.jpg",
    image: "/images/dishes/tandoori-chicken.jpg",
    rating: 4.9,
    reviews_count: 210,
    is_veg: false,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },

  // ---------------- MAIN COURSE & CURRIES ----------------
  {
    id: "dish-06",
    category_id: "cat-north-indian",
    category_name: "North Indian",
    name: "Paneer Butter Masala",
    description: "Soft cottage cheese simmered in a creamy, velvety makhani gravy enriched with fresh cream and kasuri methi.",
    price: 280,
    image_url: "/images/dishes/paneer-butter-masala.jpg",
    image: "/images/dishes/paneer-butter-masala.jpg",
    rating: 4.9,
    reviews_count: 230,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-07",
    category_id: "cat-north-indian",
    category_name: "North Indian",
    name: "Dal Makhani",
    description: "Whole black urad lentils slow-cooked overnight for 18 hours with vine tomatoes, fresh butter, and fragrant ginger.",
    price: 240,
    image_url: "/images/dishes/dal-makhani.jpg",
    image: "/images/dishes/dal-makhani.jpg",
    rating: 4.9,
    reviews_count: 198,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-08",
    category_id: "cat-mughlai",
    category_name: "Mughlai",
    name: "Shahi Paneer",
    description: "Royal Awadhi recipe featuring fresh paneer submerged in a delicate, mildly sweet cashew and almond saffron gravy.",
    price: 290,
    image_url: "/images/dishes/shahi-paneer.jpg",
    image: "/images/dishes/shahi-paneer.jpg",
    rating: 4.8,
    reviews_count: 112,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-09",
    category_id: "cat-punjabi",
    category_name: "Punjabi",
    name: "Kadhai Paneer",
    description: "Paneer cubes tossed with bell peppers, whole coriander seeds, dried red chilies, and freshly roasted kadhai masala.",
    price: 270,
    image_url: "/images/dishes/kadhai-paneer.jpg",
    image: "/images/dishes/kadhai-paneer.jpg",
    rating: 4.8,
    reviews_count: 104,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-10",
    category_id: "cat-north-indian",
    category_name: "North Indian",
    name: "Butter Chicken",
    description: "Tender tandoor-grilled chicken cooked in an iconic buttery tomato and cashew gravy with fenugreek leaves.",
    price: 340,
    image_url: "/images/dishes/butter-chicken.jpg",
    image: "/images/dishes/butter-chicken.jpg",
    rating: 5.0,
    reviews_count: 320,
    is_veg: false,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-11",
    category_id: "cat-non-veg",
    category_name: "Non-Vegetarian",
    name: "Chicken Curry",
    description: "Homestyle chicken cooked with brown onion paste, freshly ground cinnamon, cloves, and country tomatoes.",
    price: 320,
    image_url: "/images/dishes/chicken-curry.jpg",
    image: "/images/dishes/chicken-curry.jpg",
    rating: 4.7,
    reviews_count: 128,
    is_veg: false,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-12",
    category_id: "cat-mughlai",
    category_name: "Mughlai",
    name: "Mutton Rogan Josh",
    description: "Authentic Kashmiri braised lamb shanks cooked with Ratan Jot, mawa, fennel seeds, and dry ginger powder.",
    price: 420,
    image_url: "/images/dishes/mutton-rogan-josh.jpg",
    image: "/images/dishes/mutton-rogan-josh.jpg",
    rating: 5.0,
    reviews_count: 165,
    is_veg: false,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },

  // ---------------- RAJASTHANI SPECIALTIES ----------------
  {
    id: "dish-13",
    category_id: "cat-rajasthani",
    category_name: "Rajasthani",
    name: "Dal Baati Churma",
    description: "Traditional wheat dumplings baked over cow-dung embers, soaked in pure desi ghee, served with panchmel dal and sweet churma.",
    price: 320,
    image_url: "/images/dishes/dal-baati-churma.jpg",
    image: "/images/dishes/dal-baati-churma.jpg",
    rating: 5.0,
    reviews_count: 245,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-14",
    category_id: "cat-rajasthani",
    category_name: "Rajasthani",
    name: "Gatte Ki Sabzi",
    description: "Steamed gram flour dumplings poached and cooked in a spiced yogurt-based curry infused with ajwain and hing.",
    price: 240,
    image_url: "/images/dishes/gatte-ki-sabzi.jpg",
    image: "/images/dishes/gatte-ki-sabzi.jpg",
    rating: 4.8,
    reviews_count: 98,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-15",
    category_id: "cat-rajasthani",
    category_name: "Rajasthani",
    name: "Ker Sangri",
    description: "Royal desert beans and dried wild berries cooked with dry mango powder, red chilies, and cold-pressed mustard oil.",
    price: 290,
    image_url: "/images/dishes/ker-sangri.jpg",
    image: "/images/dishes/ker-sangri.jpg",
    rating: 4.9,
    reviews_count: 87,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-16",
    category_id: "cat-rajasthani",
    category_name: "Rajasthani",
    name: "Bajre Ki Roti",
    description: "Hand-patted pearl millet flatbread roasted over open flame, served hot with a generous spread of white makkhan.",
    price: 60,
    image_url: "/images/dishes/bajre-ki-roti.jpg",
    image: "/images/dishes/bajre-ki-roti.jpg",
    rating: 4.8,
    reviews_count: 67,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },

  // ---------------- BIRYANI ----------------
  {
    id: "dish-17",
    category_id: "cat-biryani",
    category_name: "Biryani",
    name: "Veg Biryani",
    description: "Seasonal garden vegetables and cottage cheese layered with fragrant saffron basmati rice and fried onions in dum.",
    price: 260,
    image_url: "/images/dishes/veg-biryani.jpg",
    image: "/images/dishes/veg-biryani.jpg",
    rating: 4.8,
    reviews_count: 145,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-18",
    category_id: "cat-biryani",
    category_name: "Biryani",
    name: "Chicken Biryani",
    description: "Succulent bone-in chicken steeped in Awadhi spices, layered with aged basmati rice and sealed with dough.",
    price: 360,
    image_url: "/images/dishes/chicken-biryani.jpg",
    image: "/images/dishes/chicken-biryani.jpg",
    rating: 4.9,
    reviews_count: 280,
    is_veg: false,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-19",
    category_id: "cat-biryani",
    category_name: "Biryani",
    name: "Mutton Biryani",
    description: "Tender goat meat slow-braised with brown onions, mint, and pure ghee, steamed with saffron rice.",
    price: 440,
    image_url: "/images/dishes/mutton-biryani.jpg",
    image: "/images/dishes/mutton-biryani.jpg",
    rating: 5.0,
    reviews_count: 215,
    is_veg: false,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },

  // ---------------- INDIAN BREADS ----------------
  {
    id: "dish-20",
    category_id: "cat-indian-breads",
    category_name: "Indian Breads",
    name: "Butter Naan",
    description: "Soft leavened flatbread baked in the tandoor and brushed generously with farm fresh butter.",
    price: 70,
    image_url: "/images/dishes/butter-naan.jpg",
    image: "/images/dishes/butter-naan.jpg",
    rating: 4.8,
    reviews_count: 310,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-21",
    category_id: "cat-indian-breads",
    category_name: "Indian Breads",
    name: "Garlic Naan",
    description: "Crispy tandoori naan infused with minced roasted garlic, fresh coriander leaves, and desi butter.",
    price: 85,
    image_url: "/images/dishes/garlic-naan.jpg",
    image: "/images/dishes/garlic-naan.jpg",
    rating: 4.9,
    reviews_count: 290,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-22",
    category_id: "cat-indian-breads",
    category_name: "Indian Breads",
    name: "Tandoori Roti",
    description: "Whole wheat stone-ground flatbread baked on the clay oven wall, crispy on the outside.",
    price: 40,
    image_url: "/images/dishes/tandoori-roti.jpg",
    image: "/images/dishes/tandoori-roti.jpg",
    rating: 4.7,
    reviews_count: 180,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-23",
    category_id: "cat-indian-breads",
    category_name: "Indian Breads",
    name: "Lachha Paratha",
    description: "Multi-layered flaky whole wheat bread cooked in the tandoor with aromatic ghee folds.",
    price: 65,
    image_url: "/images/dishes/lachcha-paratha.jpg",
    image: "/images/dishes/lachcha-paratha.jpg",
    rating: 4.8,
    reviews_count: 140,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-24",
    category_id: "cat-indian-breads",
    category_name: "Indian Breads",
    name: "Missi Roti",
    description: "Rajasthani spiced flatbread made with chickpea and wheat flour, chopped onions, and crushed pomegranate seeds.",
    price: 55,
    image_url: "/images/dishes/missi-roti.jpg",
    image: "/images/dishes/missi-roti.jpg",
    rating: 4.8,
    reviews_count: 95,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },

  // ---------------- DESSERTS ----------------
  {
    id: "dish-25",
    category_id: "cat-desserts",
    category_name: "Desserts",
    name: "Gulab Jamun",
    description: "Golden fried khoya dumplings soaked in fragrant cardamom and saffron sugar syrup (2 pieces).",
    price: 120,
    image_url: "/images/dishes/gulab-jamun.jpg",
    image: "/images/dishes/gulab-jamun.jpg",
    rating: 4.9,
    reviews_count: 240,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-26",
    category_id: "cat-desserts",
    category_name: "Desserts",
    name: "Rasmalai",
    description: "Delicate chenna patties soaked in thick clotted milk (rabri) infused with pistachios and Kashmiri saffron.",
    price: 140,
    image_url: "/images/dishes/rasmalai.jpg",
    image: "/images/dishes/rasmalai.jpg",
    rating: 5.0,
    reviews_count: 210,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-27",
    category_id: "cat-desserts",
    category_name: "Desserts",
    name: "Gajar Ka Halwa",
    description: "Slow-cooked red carrots simmered with full-cream milk, pure mawa, cashew nuts, and slivered almonds.",
    price: 150,
    image_url: "/images/dishes/gajar-ka-halwa.jpg",
    image: "/images/dishes/gajar-ka-halwa.jpg",
    rating: 4.9,
    reviews_count: 178,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-28",
    category_id: "cat-desserts",
    category_name: "Desserts",
    name: "Kulfi",
    description: "Traditional frozen Indian pot kulfi flavored with ground pistachios, green cardamom, and saffron strands.",
    price: 110,
    image_url: "/images/dishes/kulfi.jpg",
    image: "/images/dishes/kulfi.jpg",
    rating: 4.8,
    reviews_count: 130,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-29",
    category_id: "cat-desserts",
    category_name: "Desserts",
    name: "Jalebi",
    description: "Crispy spiral pretzels soaked in hot saffron sugar syrup, best enjoyed with cold rabri.",
    price: 100,
    image_url: "/images/dishes/jalebi.jpg",
    image: "/images/dishes/jalebi.jpg",
    rating: 4.8,
    reviews_count: 155,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },

  // ---------------- BEVERAGES ----------------
  {
    id: "dish-30",
    category_id: "cat-beverages",
    category_name: "Beverages",
    name: "Masala Chai",
    description: "Slow-simmered Assam whole leaf tea brewed with crushed ginger, green cardamom, cloves, and whole buffalo milk.",
    price: 60,
    image_url: "/images/dishes/masala-chai.jpg",
    image: "/images/dishes/masala-chai.jpg",
    rating: 4.9,
    reviews_count: 350,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-31",
    category_id: "cat-beverages",
    category_name: "Beverages",
    name: "Mango Lassi",
    description: "Thick hand-churned yogurt blended with sweet Alphonso mango pulp, saffron, and crushed dry fruits.",
    price: 110,
    image_url: "/images/dishes/mango-lassi.jpg",
    image: "/images/dishes/mango-lassi.jpg",
    rating: 4.9,
    reviews_count: 280,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-32",
    category_id: "cat-beverages",
    category_name: "Beverages",
    name: "Sweet Lassi",
    description: "Traditional Punjabi lassi whipped with natural sugar crystals, topped with a thick dollop of fresh malai.",
    price: 90,
    image_url: "/images/dishes/sweet-lassi.jpg",
    image: "/images/dishes/sweet-lassi.jpg",
    rating: 4.8,
    reviews_count: 190,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-33",
    category_id: "cat-beverages",
    category_name: "Beverages",
    name: "Fresh Lime Soda",
    description: "Hand-squeezed fresh lime juice served with sparkling soda water, black salt, and roasted cumin.",
    price: 80,
    image_url: "/images/dishes/fresh-lime-soda.jpg",
    image: "/images/dishes/fresh-lime-soda.jpg",
    rating: 4.7,
    reviews_count: 140,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-34",
    category_id: "cat-beverages",
    category_name: "Beverages",
    name: "Masala Chaas",
    description: "Spiced buttermilk tempered with fresh coriander, green chilies, ginger, and roasted cumin powder.",
    price: 70,
    image_url: "/images/dishes/masala-chaas.jpg",
    image: "/images/dishes/masala-chaas.jpg",
    rating: 4.8,
    reviews_count: 165,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },

  // ---------------- SOUTH INDIAN ----------------
  {
    id: "dish-35",
    category_id: "cat-south-indian",
    category_name: "South Indian",
    name: "Masala Dosa",
    description: "Crispy golden fermented rice & lentil crepe filled with spiced potato masala, served with coconut chutney and tangy sambar.",
    price: 180,
    image_url: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews_count: 215,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-36",
    category_id: "cat-south-indian",
    category_name: "South Indian",
    name: "Idli Sambar",
    description: "Steamed soft fluffy rice cakes served with piping hot drumstick sambar and fresh coconut & tomato chutneys.",
    price: 140,
    image_url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews_count: 160,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-37",
    category_id: "cat-south-indian",
    category_name: "South Indian",
    name: "Medu Vada",
    description: "Crispy golden fried urad dal donuts spiced with black pepper, crushed ginger, and curry leaves.",
    price: 150,
    image_url: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews_count: 130,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-38",
    category_id: "cat-south-indian",
    category_name: "South Indian",
    name: "Chettinad Chicken Curry",
    description: "Fiery Tamil Nadu specialty braised with freshly roasted black pepper, star anise, fennel seeds, and toasted coconut.",
    price: 360,
    image_url: "/images/dishes/chicken-curry.jpg",
    image: "/images/dishes/chicken-curry.jpg",
    rating: 4.9,
    reviews_count: 145,
    is_veg: false,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },

  // ---------------- CURRIES ----------------
  {
    id: "dish-39",
    category_id: "cat-curries",
    category_name: "Curries",
    name: "Malai Kofta",
    description: "Melt-in-mouth cottage cheese and potato dumplings simmered in a velvety cashew-cream saffron gravy.",
    price: 290,
    image_url: "/images/dishes/paneer-butter-masala.jpg",
    image: "/images/dishes/paneer-butter-masala.jpg",
    rating: 4.9,
    reviews_count: 180,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-40",
    category_id: "cat-curries",
    category_name: "Curries",
    name: "Chicken Tikka Masala",
    description: "Charcoal-grilled chicken tikka morsels simmered in a spiced tomato, butter, and cream onion gravy.",
    price: 350,
    image_url: "/images/dishes/butter-chicken.jpg",
    image: "/images/dishes/butter-chicken.jpg",
    rating: 5.0,
    reviews_count: 240,
    is_veg: false,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-41",
    category_id: "cat-curries",
    category_name: "Curries",
    name: "Palak Paneer",
    description: "Fresh cottage cheese cubes folded into a smooth, tempered spinach puree garnished with garlic and fresh cream.",
    price: 270,
    image_url: "/images/dishes/palak-paneer.jpg",
    image: "/images/dishes/palak-paneer.jpg",
    rating: 4.8,
    reviews_count: 150,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },

  // ---------------- RICE & PULAO ----------------
  {
    id: "dish-42",
    category_id: "cat-rice",
    category_name: "Rice & Pulao",
    name: "Jeera Rice",
    description: "Aromatic long-grain basmati rice tempered with roasted cumin seeds, whole cloves, and pure desi ghee.",
    price: 160,
    image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews_count: 195,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-43",
    category_id: "cat-rice",
    category_name: "Rice & Pulao",
    name: "Kashmiri Pulao",
    description: "Saffron-scented basmati rice garnished with fried cashews, raisins, slivered almonds, and fresh pomegranate seeds.",
    price: 220,
    image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews_count: 140,
    is_veg: true,
    is_chef_special: true,
    availability: "available",
    created_at: new Date().toISOString(),
  },
  {
    id: "dish-44",
    category_id: "cat-rice",
    category_name: "Rice & Pulao",
    name: "Veg Peas Pulao",
    description: "Fragrant basmati pilaf gently cooked with sweet green peas, green cardamom, bay leaf, and fresh mint.",
    price: 180,
    image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews_count: 110,
    is_veg: true,
    is_chef_special: false,
    availability: "available",
    created_at: new Date().toISOString(),
  },
];

export const initialServices: ServiceItem[] = [
  {
    id: "srv-dine-in",
    name: "Royal Heritage Dine-In",
    slug: "dine-in",
    description: "Immerse yourself in hand-carved jharokhas, brass thali hospitality, and soothing sitar notes in our royal dining courtyard.",
    icon: "UtensilsCrossed",
    image_url: "/images/hero.jpg",
    status: "active",
    badge: "Signature Experience",
    features: [
      "Traditional Aarti & Tika welcome",
      "Live classical sitar & flute recitals",
      "Kansa (bronze) royal dinnerware",
      "Complimentary paan & mukhwas service",
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: "srv-table-reservation",
    name: "Haveli Table Reservation",
    slug: "table-reservation",
    description: "Reserve your preferred table, jharokha window, or private diwan with instant confirmation.",
    icon: "CalendarCheck",
    image_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    status: "active",
    badge: "Instant Confirmation",
    features: [
      "Guaranteed priority table allocation",
      "Customized celebration & birthday setups",
      "Jain & fasting (vrat) menu accommodations",
      "Direct WhatsApp & SMS booking reminders",
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: "srv-private-dining",
    name: "Shahi Dastarkhwan VIP Salon",
    slug: "private-dining",
    description: "An exclusive acoustic private salon designed for royal gatherings, high-level business summits, and family milestones.",
    icon: "Crown",
    image_url: "https://images.unsplash.com/photo-1578474846511-04ba529f0b88?auto=format&fit=crop&w=800&q=80",
    status: "active",
    badge: "Royal Privilege",
    features: [
      "Private Master Chef and dedicated khansama",
      "Custom 7-course Rajwada degustation feast",
      "Private courtyard access and terrace seating",
      "Discreet security and personalized greeting",
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: "srv-catering",
    name: "Shahi Wedding & Event Catering",
    slug: "catering",
    description: "Bring the authentic heritage of Riwaayat to your weddings, banquets, and celebrations with live tandoors and sweet makers.",
    icon: "Sparkles",
    image_url: "https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=800&q=80",
    status: "active",
    badge: "Live Halwai Stations",
    features: [
      "Live tandoor, chaat, and jalebi counter stations",
      "Traditional brassware and royal buffet setups",
      "Uniformed khansamas and service captains",
      "Tailored menus for 50 to 2,000 guests",
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: "srv-takeaway",
    name: "Royal Curbside Takeaway",
    slug: "takeaway",
    description: "Pre-order authentic hot curries, rotis, and biryanis packaged in earthen handis and thermal containers for quick pickup.",
    icon: "ShoppingBag",
    image_url: "https://images.unsplash.com/photo-1526367790999-0150786686a2?auto=format&fit=crop&w=800&q=80",
    status: "active",
    badge: "20-Min Express Pickup",
    features: [
      "Clay handi packing that retains natural aromas",
      "Zero contact curbside hand-off to your vehicle",
      "Complimentary mint chutney & sirka onions",
      "Freshly prepared 10 minutes prior to pickup",
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: "srv-home-delivery",
    name: "Express Doorstep Delivery",
    slug: "home-delivery",
    description: "Relish piping-hot tandoori rotis, fragrant dum biryanis, and curries delivered directly to your doorstep in thermal bags.",
    icon: "Truck",
    image_url: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&w=800&q=80",
    status: "active",
    badge: "Thermal Sealed",
    features: [
      "Insulated temperature-retaining bags",
      "Live order status & courier partner tracking",
      "Tamper-proof safety seals on every box",
      "Compulsory verified delivery handover",
    ],
    created_at: new Date().toISOString(),
  },
];

export const initialTestimonials: Testimonial[] = [
  {
    id: "test-01",
    name: "Padma Shri Raghuveer Rathore",
    role_or_title: "Heritage Historian & Culinary Critic",
    message: "Riwaayat captures the true soul of Indian hospitality. The Dal Baati Churma and Butter Chicken are cooked with reverence to age-old recipes.",
    rating: 5.0,
    image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    status: "active",
    created_at: new Date().toISOString(),
  },
  {
    id: "test-02",
    name: "Meera & Rajesh Khurana",
    role_or_title: "Patrons since 2018",
    message: "The Shahi Dastarkhwan experience was unforgettable. Every dish arrived piping hot, steeped in rich aroma and unmatched taste.",
    rating: 5.0,
    image_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    status: "active",
    created_at: new Date().toISOString(),
  },
  {
    id: "test-03",
    name: "Dr. Ananya Sen",
    role_or_title: "Food Columnist, Indian Epicure",
    message: "From their signature Dahi Ke Kebab to the slow-cooked Mutton Rogan Josh, Riwaayat is undeniably the standard for authentic Indian fine dining.",
    rating: 5.0,
    image_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    status: "active",
    created_at: new Date().toISOString(),
  },
];

export const demoUsers: UserProfile[] = [
  {
    id: "user-demo-01",
    full_name: "Muskan Kumari",
    email: "muskan@riwaayat.com",
    phone: "+91 98201 44552",
    avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
    role: "user",
    created_at: "2024-01-15T10:00:00.000Z",
  },
  {
    id: "admin-demo-01",
    full_name: "Chef Aditi Sharma (General Manager)",
    email: "admin@riwaayat.com",
    phone: "+91 98200 11223",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80",
    role: "admin",
    created_at: "2023-11-01T08:00:00.000Z",
  },
  {
    id: "delivery-demo-01",
    full_name: "Rahul Sharma (Lead Courier)",
    email: "delivery@riwaayat.com",
    phone: "+91 98330 77123",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    role: "delivery_person",
    created_at: "2024-02-01T09:00:00.000Z",
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: "notif-01",
    user_id: "user-demo-01",
    title: "Welcome to Riwaayat Royal Privileges",
    message: "Namaste! Thank you for joining Riwaayat. Enjoy complimentary Masala Chai and Gulab Jamun on your inaugural order.",
    type: "promo",
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "notif-02",
    user_id: "user-demo-01",
    title: "Special Daawat: Dum Biryani Festival",
    message: "Our Master Khansamas have unveiled 5 regional dum biryanis slow-cooked in sealed clay handis.",
    type: "info",
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: "notif-03",
    user_id: "user-demo-01",
    title: "Table Reservation Confirmed",
    message: "Your table reservation for 2 guests is booked for tomorrow evening at 8:00 PM in the Courtyard.",
    type: "order",
    is_read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const initialSupportRequests: SupportRequest[] = [
  {
    id: "sup-01",
    user_id: "user-demo-01",
    user_name: "Muskan Kumari",
    user_email: "muskan@riwaayat.com",
    subject: "Private Shahi Dastarkhwan for 16 Guests",
    message: "We would like to book the exclusive VIP salon for a family celebration next Friday. Can we arrange custom Awadhi tasting menu?",
    priority: "high",
    status: "in_progress",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "sup-02",
    user_id: "user-demo-02",
    user_name: "Kavita Rao",
    user_email: "kavita.rao@example.com",
    subject: "Jain Preparation Inquiry for Dal Baati Churma",
    message: "Can the Dal Baati and Gatte Ki Sabzi be prepared in pure Jain style without onion and garlic?",
    priority: "medium",
    status: "resolved",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
];

export const initialContactMessages: ContactMessage[] = [
  {
    id: "msg-01",
    name: "Rohan Oberoi",
    email: "rohan.oberoi@globalenterprises.com",
    phone: "+91 99302 88410",
    subject: "Grand Wedding Sangeet Catering",
    message: "We are organizing a 300-guest royal sangeet ceremony and would love Riwaayat's live tandoor and mithai counters.",
    status: "new",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: "msg-02",
    name: "Pooja Varma",
    email: "pooja.varma@fashionweek.in",
    phone: "+91 98110 54321",
    subject: "Heritage Dinner Venue Inquiry",
    message: "Looking to host an exclusive delegation of cultural delegates in your Haveli Courtyard next month.",
    status: "read",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
  },
];

// ====================================================================
// DELIVERY PERSONS
// ====================================================================
export const initialDeliveryPersons: DeliveryPerson[] = [
  {
    id: "del-01",
    name: "Rahul Sharma",
    phone: "+91 98330 77123",
    email: "rahul.sharma@riwaayat-delivery.com",
    status: "available",
    vehicle_type: "Riwaayat Thermal Climate EV Pod",
    rating: 4.9,
    created_at: "2024-01-10T08:00:00.000Z",
  },
  {
    id: "del-02",
    name: "Vikram Singh",
    phone: "+91 98211 44091",
    email: "vikram.singh@riwaayat-delivery.com",
    status: "available",
    vehicle_type: "Insulated Thermal Fleet Bike",
    rating: 4.8,
    created_at: "2024-02-15T08:00:00.000Z",
  },
  {
    id: "del-03",
    name: "Priya Nair",
    phone: "+91 97112 55902",
    email: "priya.nair@riwaayat-delivery.com",
    status: "busy",
    vehicle_type: "Heritage White-Glove Van",
    rating: 5.0,
    created_at: "2024-03-01T08:00:00.000Z",
  },
];

// ====================================================================
// DELIVERY ADDRESSES
// ====================================================================
export const initialDeliveryAddresses: DeliveryAddress[] = [
  {
    id: "addr-demo-01",
    user_id: "user-demo-01",
    full_name: "Muskan Kumari",
    phone: "+91 98201 44552",
    house_number: "Haveli Suite 1402",
    street: "Civil Lines Main Road",
    area: "Civil Lines",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302006",
    landmark: "Opposite Rajwada Palace",
    delivery_instructions: "Ring doorbell twice, hand over directly with hot bags.",
    created_at: "2024-01-20T10:00:00.000Z",
  },
];

// ====================================================================
// INITIAL SEED ORDERS (100% Indian Dishes & Compulsory Handover)
// ====================================================================
export const initialOrders: Order[] = [
  {
    id: "ord-001",
    order_number: "ORD-2026-0001",
    user_id: "user-demo-01",
    customer_name: "Muskan Sharma",
    customer_email: "muskan@riwaayat.com",
    customer_phone: "+91 98201 44552",
    delivery_address: {
      id: "addr-demo-01",
      user_id: "user-demo-01",
      full_name: "Muskan Sharma",
      phone: "+91 98201 44552",
      house_number: "Flat 402, Royal Residency",
      street: "Palace Road, Near Raj Mandir",
      area: "C-Scheme",
      city: "Jaipur",
      state: "Rajasthan",
      pincode: "302001",
      landmark: "Near Central Park Gate 3",
      delivery_instructions: "Hand over directly to patron at door.",
      created_at: "2026-09-28T13:00:00.000Z",
    },
    items: [
      {
        id: "item-001-1",
        order_id: "ord-001",
        dish_id: "dish-06",
        dish_name: "Paneer Butter Masala",
        dish_image: "/images/dishes/paneer-butter-masala.jpg",
        is_veg: true,
        quantity: 2,
        unit_price: 280,
        subtotal: 560,
      },
      {
        id: "item-001-2",
        order_id: "ord-001",
        dish_id: "dish-10",
        dish_name: "Butter Chicken",
        dish_image: "/images/dishes/butter-chicken.jpg",
        is_veg: false,
        quantity: 1,
        unit_price: 340,
        subtotal: 340,
      },
      {
        id: "item-001-3",
        order_id: "ord-001",
        dish_id: "dish-21",
        dish_name: "Garlic Naan",
        dish_image: "/images/dishes/garlic-naan.jpg",
        is_veg: true,
        quantity: 4,
        unit_price: 85,
        subtotal: 340,
      },
      {
        id: "item-001-4",
        order_id: "ord-001",
        dish_id: "dish-25",
        dish_name: "Gulab Jamun",
        dish_image: "/images/dishes/gulab-jamun.jpg",
        is_veg: true,
        quantity: 2,
        unit_price: 120,
        subtotal: 240,
      },
    ],
    subtotal: 1480,
    delivery_fee: 99,
    tax: 74,
    total_amount: 1653,
    order_status: "delivered",
    payment: {
      id: "pay-001",
      order_id: "ord-001",
      payment_method: "upi",
      payment_status: "paid",
      transaction_id: "TXN-UPI-8849201",
      amount: 1653,
      paid_at: "2026-09-28T13:45:00.000Z",
      created_at: "2026-09-28T13:40:00.000Z",
    },
    delivery_assignment: {
      id: "asgn-001",
      order_id: "ord-001",
      delivery_person_id: "del-01",
      delivery_person_name: "Rahul Sharma",
      delivery_person_phone: "+91 98330 77123",
      delivery_status: "delivered",
      assigned_at: "2026-09-28T14:00:00.000Z",
      picked_up_at: "2026-09-28T14:30:00.000Z",
      delivered_at: "2026-09-28T15:05:00.000Z",
      delivery_notes: "Thermal hot bag seal intact. Hand-delivered to patron at door.",
    },
    delivery_recipient: {
      id: "recip-001",
      order_id: "ord-001",
      receiver_name: "Muskan Sharma",
      receiver_phone: "+91 98201 44552",
      delivery_date: "28 September 2026",
      delivery_time: "8:35 PM",
      received_at: "2026-09-28T15:05:00.000Z",
      delivery_notes: "Received by customer. Seal intact.",
      created_at: "2026-09-28T15:05:00.000Z",
    },
    created_at: "2026-09-28T13:40:00.000Z",
    updated_at: "2026-09-28T15:05:00.000Z",
  },
  {
    id: "ord-002",
    order_number: "ORD-2026-0002",
    user_id: "user-demo-01",
    customer_name: "Muskan Kumari",
    customer_email: "muskan@riwaayat.com",
    customer_phone: "+91 98201 44552",
    delivery_address: {
      id: "addr-demo-01",
      user_id: "user-demo-01",
      full_name: "Muskan Kumari",
      phone: "+91 98201 44552",
      house_number: "Haveli Suite 1402",
      street: "Civil Lines Main Road",
      area: "Civil Lines",
      city: "Jaipur",
      state: "Rajasthan",
      pincode: "302006",
      landmark: "Opposite Rajwada Palace",
      delivery_instructions: "Call on arrival at entrance gate.",
      created_at: "2026-09-29T06:30:00.000Z",
    },
    items: [
      {
        id: "item-002-1",
        order_id: "ord-002",
        dish_id: "dish-18",
        dish_name: "Chicken Biryani",
        dish_image: "/images/dishes/chicken-biryani.jpg",
        is_veg: false,
        quantity: 2,
        unit_price: 360,
        subtotal: 720,
      },
      {
        id: "item-002-2",
        order_id: "ord-002",
        dish_id: "dish-31",
        dish_name: "Mango Lassi",
        dish_image: "/images/dishes/mango-lassi.jpg",
        is_veg: true,
        quantity: 2,
        unit_price: 110,
        subtotal: 220,
      },
      {
        id: "item-002-3",
        order_id: "ord-002",
        dish_id: "dish-20",
        dish_name: "Butter Naan",
        dish_image: "/images/dishes/butter-naan.jpg",
        is_veg: true,
        quantity: 2,
        unit_price: 70,
        subtotal: 140,
      },
    ],
    subtotal: 1080,
    delivery_fee: 99,
    tax: 54,
    total_amount: 1233,
    order_status: "out_for_delivery",
    payment: {
      id: "pay-002",
      order_id: "ord-002",
      payment_method: "card",
      payment_status: "paid",
      transaction_id: "TXN-CARD-7731902",
      amount: 1233,
      paid_at: "2026-09-29T06:35:00.000Z",
      created_at: "2026-09-29T06:30:00.000Z",
    },
    delivery_assignment: {
      id: "asgn-002",
      order_id: "ord-002",
      delivery_person_id: "del-01",
      delivery_person_name: "Rahul Sharma",
      delivery_person_phone: "+91 98330 77123",
      delivery_status: "out_for_delivery",
      assigned_at: "2026-09-29T07:00:00.000Z",
      picked_up_at: "2026-09-29T07:20:00.000Z",
      delivery_notes: "En route via Civil Lines Flyover with hot thermal box.",
    },
    created_at: "2026-09-29T06:30:00.000Z",
    updated_at: "2026-09-29T07:20:00.000Z",
  },
  {
    id: "ord-003",
    order_number: "ORD-2026-0003",
    user_id: "user-demo-02",
    customer_name: "Kavita Rao",
    customer_email: "kavita.rao@example.com",
    customer_phone: "+91 98110 99412",
    delivery_address: {
      id: "addr-demo-02",
      user_id: "user-demo-02",
      full_name: "Kavita Rao",
      phone: "+91 98110 99412",
      house_number: "Villa 8, Rajwada Enclave",
      street: "Ajmer Road",
      area: "Sodala",
      city: "Jaipur",
      state: "Rajasthan",
      pincode: "302006",
      landmark: "Near Metro Pillar 84",
      delivery_instructions: "Deliver to security station for bungalow 8.",
      created_at: "2026-09-29T07:15:00.000Z",
    },
    items: [
      {
        id: "item-003-1",
        order_id: "ord-003",
        dish_id: "dish-13",
        dish_name: "Dal Baati Churma",
        dish_image: "/images/dishes/dal-baati-churma.jpg",
        is_veg: true,
        quantity: 2,
        unit_price: 320,
        subtotal: 640,
      },
      {
        id: "item-003-2",
        order_id: "ord-003",
        dish_id: "dish-14",
        dish_name: "Gatte Ki Sabzi",
        dish_image: "/images/dishes/gatte-ki-sabzi.jpg",
        is_veg: true,
        quantity: 1,
        unit_price: 240,
        subtotal: 240,
      },
      {
        id: "item-003-3",
        order_id: "ord-003",
        dish_id: "dish-24",
        dish_name: "Missi Roti",
        dish_image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
        is_veg: true,
        quantity: 3,
        unit_price: 55,
        subtotal: 165,
      },
    ],
    subtotal: 1045,
    delivery_fee: 99,
    tax: 52.25,
    total_amount: 1196.25,
    order_status: "preparing",
    payment: {
      id: "pay-003",
      order_id: "ord-003",
      payment_method: "cod",
      payment_status: "cod_pending",
      transaction_id: "TXN-COD-PENDING-003",
      amount: 1196.25,
      created_at: "2026-09-29T07:15:00.000Z",
    },
    created_at: "2026-09-29T07:15:00.000Z",
    updated_at: "2026-09-29T07:20:00.000Z",
  },
  {
    id: "ord-004",
    order_number: "ORD-2026-0004",
    user_id: "user-demo-03",
    customer_name: "Rohan Oberoi",
    customer_email: "rohan.oberoi@globalenterprises.com",
    customer_phone: "+91 99302 88410",
    delivery_address: {
      id: "addr-demo-03",
      user_id: "user-demo-03",
      full_name: "Rohan Oberoi",
      phone: "+91 99302 88410",
      house_number: "Suite 2801, Royal Towers",
      street: "Tonk Road",
      area: "Bapu Nagar",
      city: "Jaipur",
      state: "Rajasthan",
      pincode: "302015",
      landmark: "Near Nehru Garden",
      created_at: "2026-09-29T07:40:00.000Z",
    },
    items: [
      {
        id: "item-004-1",
        order_id: "ord-004",
        dish_id: "dish-12",
        dish_name: "Mutton Rogan Josh",
        dish_image: "https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=600&q=80",
        is_veg: false,
        quantity: 2,
        unit_price: 420,
        subtotal: 840,
      },
      {
        id: "item-004-2",
        order_id: "ord-004",
        dish_id: "dish-22",
        dish_name: "Tandoori Roti",
        dish_image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
        is_veg: true,
        quantity: 4,
        unit_price: 40,
        subtotal: 160,
      },
      {
        id: "item-004-3",
        order_id: "ord-004",
        dish_id: "dish-32",
        dish_name: "Sweet Lassi",
        dish_image: "/images/dishes/sweet-lassi.jpg",
        is_veg: true,
        quantity: 2,
        unit_price: 90,
        subtotal: 180,
      },
    ],
    subtotal: 1180,
    delivery_fee: 99,
    tax: 59,
    total_amount: 1338,
    order_status: "order_confirmed",
    payment: {
      id: "pay-004",
      order_id: "ord-004",
      payment_method: "google_pay",
      payment_status: "paid",
      transaction_id: "TXN-GPAY-992147",
      amount: 1338,
      paid_at: "2026-09-29T07:42:00.000Z",
      created_at: "2026-09-29T07:40:00.000Z",
    },
    created_at: "2026-09-29T07:40:00.000Z",
    updated_at: "2026-09-29T07:45:00.000Z",
  },
];
